### ISSUE TITLE
Results for master (9.2.0) and 9.1.0 branch differ

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/dealii-adapter#53]
I just did an experiment, where I ran Deal.II with a [fake fluid solver](https://github.com/BenjaminRodenberg/tutorials/tree/fluid-fake/perpendicular-flap/fluid-fake) that just provides a constant force. I can provide more details, if needed.

First I started with deal.II version 9.1.0 and the [corresponding branch of the adapter](https://github.com/precice/dealii-adapter/tree/dealii-9.1) (cac50c4) and got this result:

![Fake-Deal II_9 1 0](https://user-images.githubusercontent.com/5740604/111786595-4653e880-88be-11eb-9fed-9c7c0f2bba2a.png)

I repeated the experiment with deal.II version 9.2.0 and the master branch of this repository (1d14846) and got this result:

![Fake-Deal II_9 2 0](https://user-images.githubusercontent.com/5740604/111786798-7b603b00-88be-11eb-9412-6e94ac3cae10.png)

Both plots show the displacement of the tip in x and y direction. The amplitude of the oscillation differs a lot. One good candidate for the difference is https://github.com/precice/dealii-adapter/pull/44.

Another note: The `9.2.0` version gives results that match very well with the same setup using FEniCS. Therefore, I am quite confident that the `9.2.0` version is correct and the `9.1.0` is not.

**Comment by DavidSCN** [comment]
In case you use `Force` data, it is indeed related to #44, which is not included in the backport. I just realized that we also advertise the backport on our website. Question goes a bit to @MakisH, who brought up the idea in #32 and closed it. Either we drop v9.1 our we should add an action in order to sync it automatically with the base branch.

**Comment by MakisH** [comment]
I see that the [backports ppa](http://ppa.launchpad.net/ginggs/deal.ii-9.2.0-backports/ubuntu/dists/) supports Ubuntu 18.04 (bionic) and 20.04 (focal), so we can drop our support for 9.1.

@DavidSCN could you please delete the branch and remove this information from the website? Otherwise, I could do it towards the end of the week.

**Comment by DavidSCN** [comment]
I'm anyway updating the docs right now...

**Comment by MakisH** [comment]
Closed with https://github.com/precice/precice.github.io/commit/eab2c00fd270cf989665645974d221471e131999
